### ISSUE TITLE
Error: contains unsupported image format

### ISSUE THREAD

**Issue by iSentrie** [borisnliscool/propscreenshotter#1]
1️⃣ After running command it returns unsupport message.

![image](https://github.com/borisnliscool/propscreenshotter/assets/29688478/58aeaa07-40a4-41f6-b7cf-fd08d369113b)
Server is running on port 3000
[Error: Input file contains unsupported image format]

2️⃣ localhost:3000 / 5000 issue
![image](https://github.com/borisnliscool/propscreenshotter/assets/29688478/af8ee1cd-8bfa-47ec-8969-b7486752674d)
![image](https://github.com/borisnliscool/propscreenshotter/assets/29688478/a63a55bb-bf06-4b73-b804-b9bdba706516)

**Comment by borisnliscool** [comment]
1. I would like to ask you to seek help about this in my discord server, as that is easier for me.
2. Port 3000 shouldn't return anything
